version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: pytest tests
          name: Test

  # TODO: Separate common steps
  deploy_stage:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Create packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel      
      - run:
          name: Upload to text PyPI
          command: |
            pip install --upgrade twine
            twine upload -u $TEST_PYPI_USERNAME -p $TEST_PYPI_PASSWORD --repository testpypi dist/*

  deploy_production:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: pytest curl2swift/tests
          name: Test
      - run:
          name: Verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify
      - run:
          name: Create packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel      
      - run:
          name: Upload to PyPI
          command: |
            pip install --upgrade twine
            twine upload -u $TEST_PYPI_USERNAME -p $TEST_PYPI_PASSWORD dist/*


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - stage
                - master
      - deploy_stage:
          requires:
            - build
          filters:
            branches:
              only: 
                - stage
      - deploy_production:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              only: 
                - master